services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./php/script.php:/app/script.php

  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./python/script.py:/app/script.py

  ruby:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    volumes:
      - ./ruby/script.rb:/app/script.rb

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./node/script.js:/app/script.js
      
  lua:
    build:
      context: .
      dockerfile: Dockerfile.lua
    volumes:
      - ./lua/script.lua:/app/script.lua

  go:
    build:
      context: .
      dockerfile: Dockerfile.go
    volumes:
      - ./go/script.go:/src/script.go

  rust:
    build:
      context: .
      dockerfile: Dockerfile.rust
    volumes:
      - ./rust/Cargo.toml:/src/Cargo.toml
      - ./rust/src:/src/src
      
  java:
    build:
      context: .
      dockerfile: Dockerfile.java
    volumes:
      - ./java/Hello.java:/src/Hello.java
