services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./php/script.php:/app/script.php

  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./python/script.py:/app/script.py

  ruby:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    volumes:
      - ./ruby/script.rb:/app/script.rb

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./node/script.js:/app/script.js
      
  lua:
    build:
      context: .
      dockerfile: Dockerfile.lua
    volumes:
      - ./lua/script.lua:/app/script.lua
