services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./php/script.php:/app/script.php
      
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./python/script.py:/app/script.py


