FROM rust:1.76-alpine AS build
WORKDIR /src
COPY rust/Cargo.toml .
COPY rust/src ./src
RUN cargo build --release

FROM alpine:3.20
WORKDIR /app
COPY --from=build /src/target/release/asl-rust ./app
CMD ["./app"]
